// alert.types.ts
export interface PopupText {
  title: string;
  description: string;
  close?: string;
  confirm?: string;
}

export interface PopupsTexts {
  button?: {
    accept: string;
    continue: string;
    close: string;
    reload?: string;
  };

  a11y?: {
    close: string;
    dialog: string;
    loading: string;
  };

  GLOBAL_LOADING?: PopupText;
  REGISTER_LOADING_SUBMIT?: PopupText;

  NO_AUTH_USER?: PopupText;
  AUTH_ACCESS_TOKEN_EXPIRED?: PopupText;
  AUTH_ACCESS_TOKEN_INVALID?: PopupText;
  AUTH_ACCESS_TOKEN_MISSING?: PopupText;
  AUTH_BLOCKED?: PopupText;
  AUTH_CLIENT_ADMIN_REQUIRED?: PopupText;
  AUTH_CLIENT_NOT_FOUND?: PopupText;
  AUTH_CURRENT_PASSWORD_INVALID?: PopupText;
  AUTH_FORBIDDEN?: PopupText;
  AUTH_GET_SUCCESS?: PopupText;
  AUTH_INVALID_CREDENTIALS?: PopupText;
  AUTH_NOT_LOGGED_IN?: PopupText;
  AUTH_REQUIRED?: PopupText;
  AUTH_SUPERADMIN_REQUIRED?: PopupText;
  AUTH_USER_NOT_FOUND?: PopupText;
  AUTH_VERIFY_EMAIL_TOKEN_EXPIRED?: PopupText;
  AUTH_VERIFY_EMAIL_TOKEN_INVALID?: PopupText;

  CLIENT_CLIENT_NOT_FOUND?: PopupText;
  CLIENT_CREATE_DOMAIN_EXISTS?: PopupText;
  CLIENT_CREATE_FAILED?: PopupText;
  CLIENT_CREATED?: PopupText;
  CLIENT_DOMAIN_EXISTS?: PopupText;
  CLIENT_FETCH_DASHBOARD_SUCCESS?: PopupText;
  CLIENT_FETCH_NOT_FOUND?: PopupText;
  CLIENT_FETCH_SUCCESS?: PopupText;
  CLIENT_ID_MISMATCH?: PopupText;
  CLIENT_ID_REQUIRED?: PopupText;
  CLIENT_MISSING_CLIENT_ID?: PopupText;
  CLIENT_NOT_FOUND?: PopupText;
  CLIENT_PUBLIC_FETCH_SUCCESS?: PopupText;
  CLIENT_UPDATED?: PopupText;
  CLIENT_UPDATE_FAILED?: PopupText;
  CLIENT_UPDATE_FIELD_NOT_ALLOWED?: PopupText;

  COMPANY_CREATED?: PopupText;
  COMPANY_EMAIL_EXISTS?: PopupText;
  COMPANY_NAME_EXISTS?: PopupText;

  CONTACT_CREATE_FAILED?: PopupText;
  CONTACT_DELETE_FAILED?: PopupText;
  CONTACT_LIST_FAILED?: PopupText;
  CONTACT_MESSAGE_CREATED?: PopupText;
  CONTACT_MESSAGE_DELETED?: PopupText;
  CONTACT_MESSAGES_DELETED?: PopupText;
  CONTACT_MESSAGE_NOT_FOUND?: PopupText;
  CONTACT_MESSAGE_RESPONDED?: PopupText;
  CONTACT_NOTIFICATION_FAILED?: PopupText;
  CONTACT_RESPONSE_FAILED?: PopupText;

  EMAIL_DELIVERY_FAILED?: PopupText;

  NOTIFICATION_ADMIN_LIST?: PopupText;
  NOTIFICATION_CREATED?: PopupText;
  NOTIFICATION_DELETED?: PopupText;
  NOTIFICATION_FORBIDDEN_TARGET?: PopupText;
  NOTIFICATION_LIST?: PopupText;
  NOTIFICATION_MARKED_ALL_READ?: PopupText;
  NOTIFICATION_MARKED_READ?: PopupText;
  NOTIFICATION_MARKED_SEEN?: PopupText;
  NOTIFICATION_NOT_FOUND?: PopupText;
  NOTIFICATION_UNREAD_COUNT?: PopupText;

  OBJECT_ADDRESS_EXISTS?: PopupText;
  OBJECT_CREATED?: PopupText;
  OBJECT_FOUND?: PopupText;
  OBJECT_LIST?: PopupText;
  OBJECT_NOT_FOUND?: PopupText;
  OBJECT_NUMBER_EXISTS?: PopupText;
  OBJECT_UPDATED?: PopupText;

  PROPERTY_MANAGER_CREATED?: PopupText;
  PROPERTY_MANAGER_EMAIL_EXISTS?: PopupText;
  PROPERTY_MANAGER_EXISTS?: PopupText;
  PROPERTY_MANAGER_FOUND?: PopupText;
  PROPERTY_MANAGER_LIST?: PopupText;
  PROPERTY_MANAGER_NOT_FOUND?: PopupText;
  PROPERTY_MANAGER_UPDATED?: PopupText;

  WORKER_ALREADY_EXISTS?: PopupText;
  WORKER_CREATED?: PopupText;
  WORKER_DELETED?: PopupText;
  WORKER_FOUND?: PopupText;
  WORKER_LIST?: PopupText;
  WORKER_LOAD_FAILED?: PopupText;
  WORKER_NOT_FOUND?: PopupText;
  WORKER_UPDATED?: PopupText;

  VALIDATION_ERROR?: PopupText;

  USER_BLOCKED?: PopupText;
  USER_CHANGE_EMAIL_CONFIRMED?: PopupText;
  USER_CHANGE_EMAIL_INVALID_TOKEN?: PopupText;
  USER_CHANGE_EMAIL_MISSING_TOKEN?: PopupText;
  USER_CHANGE_EMAIL_REQUESTED?: PopupText;
  USER_CHANGE_EMAIL_SAME_EMAIL?: PopupText;
  USER_CHANGE_EMAIL_STATE_MISMATCH?: PopupText;
  USER_CHANGE_EMAIL_TOKEN_EXPIRED?: PopupText;
  USER_CLIENT_BLOCKED?: PopupText;
  USER_CLIENT_COOKIES_UPDATE_SUCCESS?: PopupText;
  USER_CLIENT_NOT_FOUND?: PopupText;
  USER_CLIENT_PROFILE_CREATED?: PopupText;
  USER_CLIENT_PROFILE_DELETED?: PopupText;
  USER_CLIENT_PROFILE_EXISTS?: PopupText;
  USER_CLIENT_PROFILE_FOUND?: PopupText;
  USER_CLIENT_PROFILE_NOT_FOUND?: PopupText;
  USER_CLIENT_PROFILE_UPDATED?: PopupText;
  USER_EMAIL_ALREADY_IN_USE?: PopupText;
  USER_FORGOT_PASSWORD_EMAIL_SENT?: PopupText;
  USER_LOGIN_EMAIL_NOT_VERIFIED?: PopupText;
  USER_LOGIN_INVALID_PASSWORD?: PopupText;
  USER_LOGIN_MISSING_EMAIL?: PopupText;
  USER_LOGIN_MISSING_PASSWORD?: PopupText;
  USER_LOGIN_SUCCESS?: PopupText;
  USER_LOGIN_USER_NOT_FOUND?: PopupText;
  USER_LOGOUT_ALL_SUCCESS?: PopupText;
  USER_LOGOUT_SUCCESS?: PopupText;
  USER_NEED_TO_LOGIN?: PopupText;
  USER_NOT_FOUND?: PopupText;
  USER_PASSWORD_RESET_SUCCESS?: PopupText;
  USER_REGISTER_ALREADY_REGISTERED?: PopupText;
  USER_REGISTER_NEEDS_CORRECT_PASSWORD?: PopupText;
  USER_REGISTER_SUCCESS?: PopupText;
  USER_RESET_PASSWORD_INVALID_TOKEN?: PopupText;
  USER_RESET_PASSWORD_SUCCESS?: PopupText;
  USER_RESET_PASSWORD_TOKEN_EXPIRED?: PopupText;
  USER_SESSION_EXPIRED?: PopupText;
  USER_TOS_NOT_ACCEPTED?: PopupText;
  USER_UPDATE_PASSWORD_SUCCESS?: PopupText;
  USER_VERIFY_EMAIL_RESENT?: PopupText;
  USER_VERIFY_EMAIL_SUCCESS?: PopupText;
  USER_VERIFY_EMAIL_VERIFIED?: PopupText;
  USER_VERIFY_EXPIRED_TOKEN?: PopupText;
  USER_VERIFY_INVALID_TOKEN?: PopupText;
  USER_VERIFY_MISSING_TOKEN?: PopupText;

  LOGOUT_CONFIRM?: PopupText;
  LOGOUT_FAILED?: PopupText;
  LOGOUT_SUCCESS?: PopupText;
  MAGIC_LOGIN_SUCCESS?: PopupText;
  MAGIC_TOKEN_EXPIRED?: PopupText;
  MAGIC_TOKEN_INVALID?: PopupText;
  USER_EDIT_EMPTY_NEW_PASSWORD?: PopupText;
  PROFILE_ADDRESS_DELETE_CONFIRM?: PopupText;

  EMAIL_VERIFICATION_RESENT?: PopupText;

  REFRESH_TOKEN_MISSING?: PopupText;
  REFRESH_TOKEN_INVALIDATED?: PopupText;
  REFRESH_TOKEN_EXPIRED?: PopupText;
  ACCESS_TOKEN_REFRESHED?: PopupText;
  CSRF_TOKEN_INVALID?: PopupText;
  CLEANING_REQUEST_LOADING?: PopupText;
  CLEANING_REQUEST_SUBMITTED?: PopupText;
  CLEANING_REQUEST_MISSING_SESSION?: PopupText;

  GLOBAL_INTERNAL_ERROR?: PopupText;
  PERMISSION_DENIED?: PopupText;
}

export type PopupCode = Exclude<keyof PopupsTexts, 'button' | 'a11y'>;
